### ISSUE TITLE
Iteration Plan

### ISSUE THREAD

**Issue by DotJoshJohnson** [DotJoshJohnson/vscode-xml#37]
### Roadmap Items
- [x] XML Tree View Feature (issue #32, pull request #38)
- [x] XML Tree View Documentation (issue #39)
### Debt Items
- [x] Update XMLDOM Dependency (issue #33, pull request #36)

**Comment by DotJoshJohnson** [comment]
PR #44
